# File: pages.toml

[[pages]]
id = "home"
name = "Home"
file = "pages/home.py"
disabled = false
use_container_width = true

[[pages]]
id = "products"
name = "Products"
file = "pages/products.py"
disabled = false
use_container_width = true

[[pages]]
id = "apple"
name = "Apple"
file = "pages/apple.py"
disabled = false
use_container_width = true

[[pages]]
id = "google"
name = "Google"
file = "pages/google.py"
disabled = false
use_container_width = true
